<div class="footer user-select-none">
  <a
    href="https://github.com/omardiaadev/discord-channel-html-transcript"
    target="_blank"
    property="dct:title"
    rel="cc:attributionURL"
    class="markup"
  >
    discord-channel-html-transcript
  </a>

  &nbsp;by&nbsp;

  <a
    href="https://github.com/omardiaadev"
    target="_blank"
    property="cc:attributionName"
    rel="cc:attributionURL dct:creator"
    class="markup"
  >
    Omar Diaa
  </a>

  &nbsp;is licensed under&nbsp;

  <a
    href="https://creativecommons.org/licenses/by-sa/4.0/"
    target="_blank"
    rel="license noopener noreferrer"
    class="markup"
  >
    CC BY-SA 4.0
  </a>

  &nbsp;•&nbsp;

  <a
    href="https://github.com/omardiaadev/discord-channel-html-transcript/#legal-compliance"
    target="_blank"
    class="markup"
  >
    Legal Compliance
  </a>
</div>
